# Generated by Django 3.0.4 on 2020-05-17 11:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20200516_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 17, 11, 8, 48, 164495, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, choices=[('İstanbul', 'İstanbul'), ('Ankara', 'Ankara')], default='İstanbul', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 17, 11, 8, 59, 186022, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
