# Generated by Django 3.0.4 on 2020-06-12 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0015_auto_20200517_1923'),
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='start_date',
        ),
        migrations.AddField(
            model_name='rent',
            name='total',
            field=models.FloatField(blank=True, default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='rentproduct',
            name='amount',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='rentproduct',
            name='end_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rentproduct',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='rent',
            name='first_name',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='rent',
            name='last_name',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='rent',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Canceled', 'Canceled'), ('Preaparing', 'Preaparing')], default='New', max_length=10),
        ),
        migrations.AlterField(
            model_name='rent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentproduct',
            name='price',
            field=models.FloatField(default='0'),
        ),
        migrations.CreateModel(
            name='ShopCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
