# Generated by Django 3.0.4 on 2020-06-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_auto_20200613_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='start_date',
            field=models.DateField(),
        ),
    ]
